config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

class AdminConstraint
  def matches?(request)
    return false if request.session[:current_admin_id].blank?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  post '/graphql', to: 'graphql#execute'

  get 'login', to: 'sessions#new', as: :login
  match '/auth/mixin/callback', to: 'sessions#create', via: %i[get post]
  get 'logout', to: 'sessions#delete', as: :logout

  # health check for render.com
  get 'healthz', to: 'healthz#index', as: :healthz

  root to: 'home#index'

  namespace :ifttb do
    get :login, to: 'sessions#new', as: :login
    match 'auth/mixin/callback', to: 'sessions#create', via: %i[get post]
    get :logout, to: 'sessions#delete', as: :logout

    get :menu, to: 'home#menu'

    resources :applets do
      post :pend
      post :connect
      post :disconnect

      resources :applet_datetime_triggers, except: %i[index show]
      resources :applet_4swap_triggers, except: %i[index show]
      resources :applet_pando_leaf_triggers, except: %i[index show]
      resources :applet_pando_rings_triggers, except: %i[index show]
      resources :applet_exin_local_triggers, except: %i[index show]

      resources :applet_4swap_actions, except: %i[index show]
      resources :applet_mix_swap_actions, except: %i[index show]
      resources :applet_alert_actions, except: %i[index show]
    end

    resources :archived_applets, only: %i[index update destroy]
    resource :stats, only: :show
    resource :wallet, only: :show do
      post :withdraw
    end
    resources :orders, only: %i[new create]

    root to: 'applets#index'
  end

  namespace :admin do
    get 'logout', to: 'sessions#delete', as: :logout

    # sidekiq
    mount Sidekiq::Web, at: 'sidekiq', constraints: AdminConstraint.new

    # exception
    mount ExceptionTrack::Engine => '/exception-track'

    root to: 'home#index'
    get '*path' => 'home#index'
  end

  get '*path' => 'home#index'
end

app/controllers/ifttb/applet_4swap_actions_controller.rb
# frozen_string_literal: true

class Ifttb::Applet4swapActionsController < Ifttb::BaseController
  before_action :load_applet
  before_action :load_action, only: %i[edit update destroy]
  before_action :load_assets, only: %i[new edit]

  def new
    @action = @applet.applet_actions.find_by(type: 'Applet4swapAction')
    @action ||=
      @applet
      .applet_actions
      .new(
        type: 'Applet4swapAction',
        pay_asset_id: '4d8c508b-91c5-375b-92b0-ee702ed2dac5',
        fill_asset_id: 'c6d0c728-2624-429b-8e0d-d9d19b6592fa',
        pay_amount: '10'
      )
    redirect_to edit_ifttb_applet_applet_4swap_action_path(@applet, @action) if @action.persisted?
  end

  def edit
  end

  def create
    @action = Applet4swapAction.new action_params
    redirect_to edit_ifttb_applet_path(@applet) if @action.save
  end

  def update
    @action.assign_attributes action_params

    if @action.save
      redirect_to edit_ifttb_applet_path(@applet)
    else
      render :edit
    end
  end

  def destroy
    @action.destroy unless @applet.drafted?
    redirect_to edit_ifttb_applet_path(@applet)
  end

  private

  def load_applet
    @applet = current_user.applets.find params[:applet_id]
    redirect_to edit_ifttb_applet_path(@applet) if @applet.connected?
  end

  def load_action
    @action = @applet.applet_actions.find params[:id]
  end

  def load_assets
    @mixin_assets =
      MixinAsset
      .includes(:chain_asset)
      .where(asset_id: Foxswap.api.tradable_asset_ids)
      .order(symbol: :asc)
  end

  def action_params
    params
      .require(:applet_4swap_action)
      .permit(
        :type,
        :applet_id,
        :pay_asset_id,
        :fill_asset_id,
        :pay_amount,
        :slippage
      )
  end
end

app/controllers/ifttb/applet_4swap_triggers_controller.rb
# frozen_string_literal: true

class Ifttb::Applet4swapTriggersController < Ifttb::BaseController
  before_action :load_applet
  before_action :load_trigger, only: %i[edit update destroy]
  before_action :load_assets, only: %i[new edit]

  def new
    @trigger = @applet.applet_triggers.find_by(type: 'Applet4swapTrigger')
    @trigger ||=
      @applet
      .applet_triggers
      .new(
        type: 'Applet4swapTrigger',
        base_asset_id: 'c6d0c728-2624-429b-8e0d-d9d19b6592fa',
        quote_asset_id: '4d8c508b-91c5-375b-92b0-ee702ed2dac5',
        target_index: 'ask_price',
        compare_action: 'larger_than',
        target_value: '100000'
      )
    redirect_to edit_ifttb_applet_applet_4swap_trigger_path(@applet, @trigger) if @trigger.persisted?
  end

  def edit
  end

  def create
    @trigger = Applet4swapTrigger.new trigger_params
    redirect_to edit_ifttb_applet_path(@applet) if @trigger.save
  end

  def update
    @trigger.assign_attributes trigger_params

    if @trigger.save
      redirect_to edit_ifttb_applet_path(@applet)
    else
      render :edit
    end
  end

  def destroy
    @trigger.destroy if @applet.drafted? || @applet.applet_triggers.count > 1
    redirect_to edit_ifttb_applet_path(@applet)
  end

  private

  def load_applet
    @applet = current_user.applets.find params[:applet_id]
    redirect_to edit_ifttb_applet_path(@applet) if @applet.connected?
  end

  def load_trigger
    @trigger = @applet.applet_triggers.find params[:id]
  end

  def load_assets
    @mixin_assets =
      MixinAsset
      .includes(:chain_asset)
      .where(asset_id: Foxswap.api.tradable_asset_ids)
      .order(symbol: :asc)
  end

  def trigger_params
    params
      .require(:applet_4swap_trigger)
      .permit(
        :type,
        :applet_id,
        :base_asset_id,
        :quote_asset_id,
        :target_index,
        :target_value,
        :compare_action
      )
  end
end

app/controllers/ifttb/applet_actions_controller.rb
# frozen_string_literal: true

class Ifttb::AppletActionsController < Ifttb::BaseController
  before_action :load_applet

  private

  def load_applet
    @applet = Applet.find params[:applet_id]
  end
end

app/controllers/ifttb/applet_alert_actions_controller.rb
# frozen_string_literal: true

class Ifttb::AppletAlertActionsController < Ifttb::BaseController
end

app/controllers/ifttb/applet_datetime_triggers_controller.rb
# frozen_string_literal: true

class Ifttb::AppletDatetimeTriggersController < Ifttb::BaseController
  before_action :load_applet
  before_action :load_trigger, only: %i[edit update destroy]

  def new
    @trigger = @applet.applet_datetime_trigger || @applet.applet_triggers.new(type: 'AppletDatetimeTrigger')
    redirect_to edit_ifttb_applet_applet_datetime_trigger_path(@applet, @trigger) if @trigger.persisted?
  end

  def edit
    @trigger = @applet.applet_triggers.find params[:id]
  end

  def create
    @trigger = AppletDatetimeTrigger.new trigger_params.merge(applet: @applet)
    if @trigger.save
      redirect_to edit_ifttb_applet_path(@applet)
    else
      render :new
    end
  end

  def update
    @trigger = @applet.applet_triggers.find params[:id]
    @trigger.assign_attributes trigger_params

    if @trigger.save
      redirect_to edit_ifttb_applet_path(@applet)
    else
      render :edit
    end
  end

  def destroy
    @trigger.destroy if @applet.drafted? || @applet.applet_triggers.count > 1
    redirect_to edit_ifttb_applet_path(@applet)
  end

  private

  def load_applet
    @applet = current_user.applets.find params[:applet_id]
    redirect_to edit_ifttb_applet_path(@applet) if @applet.connected?
  end

  def load_trigger
    @trigger = @applet.applet_triggers.find params[:id]
  end

  def trigger_params
    params
      .require(:applet_datetime_trigger)
      .permit(
        :minute,
        :hour,
        :day,
        :month,
        :wday
      )
  end
end

app/controllers/ifttb/applet_exin_local_triggers_controller.rb
# frozen_string_literal: true

class Ifttb::AppletExinLocalTriggersController < Ifttb::BaseController
  before_action :load_applet
  before_action :load_trigger, only: %i[edit update destroy]
  before_action :load_assets, only: %i[new edit]

  def new
    @trigger = @applet.applet_triggers.find_by(type: 'AppletExinLocalTrigger')
    @trigger ||=
      @applet
      .applet_triggers
      .new(
        type: 'AppletExinLocalTrigger'
      )
    redirect_to edit_ifttb_applet_applet_4swap_trigger_path(@applet, @trigger) if @trigger.persisted?
  end

  def edit
  end

  def create
    @trigger = AppletExinLocalTrigger.new trigger_params
    redirect_to edit_ifttb_applet_path(@applet) if @trigger.save
  end

  def update
    @trigger.assign_attributes trigger_params

    if @trigger.save
      redirect_to edit_ifttb_applet_path(@applet)
    else
      render :edit
    end
  end

  def destroy
    @trigger.destroy if @applet.drafted? || @applet.applet_triggers.count > 1
    redirect_to edit_ifttb_applet_path(@applet)
  end

  private

  def load_applet
    @applet = current_user.applets.find params[:applet_id]
    redirect_to edit_ifttb_applet_path(@applet) if @applet.connected?
  end

  def load_trigger
    @trigger = @applet.applet_triggers.find params[:id]
  end

  def load_assets
    @mixin_assets =
      MixinAsset
      .includes(:chain_asset)
      .where(asset_id: ExinLocal.api.tradable_asset_ids)
      .order(symbol: :asc)
  end

  def trigger_params
    params
      .require(:applet_exin_local_trigger)
      .permit(
        :type,
        :applet_id,
        :asset_id,
        :target_index,
        :target_value,
        :compare_action
      )
  end
end

app/controllers/ifttb/applet_mix_swap_actions_controller.rb
# frozen_string_literal: true

class Ifttb::AppletMixSwapActionsController < Ifttb::BaseController
  before_action :load_applet
  before_action :load_action, only: %i[edit update destroy]
  before_action :load_assets, only: %i[new edit]

  def new
    @action = @applet.applet_actions.find_by(type: 'AppletMixSwapAction')
    @action ||=
      @applet
      .applet_actions
      .new(
        type: 'AppletMixSwapAction',
        pay_asset_id: '4d8c508b-91c5-375b-92b0-ee702ed2dac5',
        fill_asset_id: 'c6d0c728-2624-429b-8e0d-d9d19b6592fa',
        pay_amount: '10'
      )
    redirect_to edit_ifttb_applet_applet_MixSwap_action_path(@applet, @action) if @action.persisted?
  end

  def edit
  end

  def create
    @action = AppletMixSwapAction.new action_params
    redirect_to edit_ifttb_applet_path(@applet) if @action.save
  end

  def update
    @action.assign_attributes action_params

    if @action.save
      redirect_to edit_ifttb_applet_path(@applet)
    else
      render :edit
    end
  end

  def destroy
    @action.destroy unless @applet.drafted?
    redirect_to edit_ifttb_applet_path(@applet)
  end

  private

  def load_applet
    @applet = current_user.applets.find params[:applet_id]
    redirect_to edit_ifttb_applet_path(@applet) if @applet.connected?
  end

  def load_action
    @action = @applet.applet_actions.find params[:id]
  end

  def load_assets
    @mixin_assets =
      MixinAsset
      .includes(:chain_asset)
      .where(asset_id: MixSwap.api.tradable_asset_ids)
      .order(symbol: :asc)
  end

  def action_params
    params
      .require(:applet_mix_swap_action)
      .permit(
        :type,
        :applet_id,
        :pay_asset_id,
        :fill_asset_id,
        :pay_amount,
        :slippage
      )
  end
end

app/controllers/ifttb/applet_pando_leaf_triggers_controller.rb
# frozen_string_literal: true

class Ifttb::AppletPandoLeafTriggersController < Ifttb::BaseController
  before_action :load_applet
  before_action :load_trigger, only: %i[edit update destroy]
  before_action :load_assets, only: %i[new edit]

  def new
    @trigger = @applet.applet_triggers.find_by(type: 'AppletPandoLeafTrigger')
    @trigger ||= @applet.applet_triggers.new(type: 'AppletPandoLeafTrigger')
    redirect_to edit_ifttb_applet_applet_PandoLeaf_trigger_path(@applet, @trigger) if @trigger.persisted?
  end

  def edit
  end

  def create
    @trigger = AppletPandoLeafTrigger.new trigger_params
    redirect_to edit_ifttb_applet_path(@applet) if @trigger.save
  end

  def update
    @trigger.assign_attributes trigger_params

    if @trigger.save
      redirect_to edit_ifttb_applet_path(@applet)
    else
      render :edit
    end
  end

  def destroy
    @trigger.destroy if @applet.drafted? || @applet.applet_triggers.count > 1
    redirect_to edit_ifttb_applet_path(@applet)
  end

  private

  def load_applet
    @applet = current_user.applets.find params[:applet_id]
    redirect_to edit_ifttb_applet_path(@applet) if @applet.connected?
  end

  def load_trigger
    @trigger = @applet.applet_triggers.find params[:id]
  end

  def load_assets
    @mixin_assets =
      MixinAsset
      .includes(:chain_asset)
      .where(asset_id: PandoLeaf.api.supportable_asset_ids)
      .order(symbol: :asc)
  end

  def trigger_params
    params
      .require(:applet_pando_leaf_trigger)
      .permit(
        :type,
        :applet_id,
        :asset_id,
        :target_index,
        :target_value,
        :compare_action
      )
  end
end

app/controllers/ifttb/applet_pando_rings_triggers_controller.rb
# frozen_string_literal: true

class Ifttb::AppletPandoRingsTriggersController < Ifttb::BaseController
  before_action :load_applet
  before_action :load_trigger, only: %i[edit update destroy]
  before_action :load_assets, only: %i[new edit]

  def new
    @trigger = @applet.applet_triggers.find_by(type: 'AppletPandoRingsTrigger')
    @trigger ||= @applet.applet_triggers.new(type: 'AppletPandoRingsTrigger')
    redirect_to edit_ifttb_applet_applet_PandoRings_trigger_path(@applet, @trigger) if @trigger.persisted?
  end

  def edit
  end

  def create
    @trigger = AppletPandoRingsTrigger.new trigger_params
    redirect_to edit_ifttb_applet_path(@applet) if @trigger.save
  end

  def update
    @trigger.assign_attributes trigger_params

    if @trigger.save
      redirect_to edit_ifttb_applet_path(@applet)
    else
      render :edit
    end
  end

  def destroy
    @trigger.destroy if @applet.drafted? || @applet.applet_triggers.count > 1
    redirect_to edit_ifttb_applet_path(@applet)
  end

  private

  def load_applet
    @applet = current_user.applets.find params[:applet_id]
    redirect_to edit_ifttb_applet_path(@applet) if @applet.connected?
  end

  def load_trigger
    @trigger = @applet.applet_triggers.find params[:id]
  end

  def load_assets
    @mixin_assets =
      MixinAsset
      .includes(:chain_asset)
      .where(asset_id: PandoRings.api.supportable_asset_ids)
      .order(symbol: :asc)
  end

  def trigger_params
    params
      .require(:applet_pando_rings_trigger)
      .permit(
        :type,
        :applet_id,
        :asset_id,
        :target_index,
        :target_value,
        :compare_action
      )
  end
end

app/controllers/ifttb/applet_triggers_controller.rb
# frozen_string_literal: true

class Ifttb::AppletTriggersController < Ifttb::BaseController
  before_action :load_applet

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

  private

  def load_applet
    @applet = Applet.find params[:applet_id]
  end
end

app/controllers/ifttb/applets_controller.rb
# frozen_string_literal: true

class Ifttb::AppletsController < Ifttb::BaseController
  before_action :load_applet, only: %i[pend archive connect disconnect]

  def index
    @pagy, @applets = pagy current_user.applets.without_drafted.without_archived.order(updated_at: :desc)
  end

  def show
    @applet = current_user.applets.find params[:id]
  end

  def new
    if current_user.may_create_applet?
      drafted_applet = current_user.applets.drafted.first
      drafted_applet ||= current_user.applets.create

      redirect_to edit_ifttb_applet_path(drafted_applet)
    else
      redirect_to ifttb_applets_path
    end
  end

  def edit
    @applet = current_user.applets.find_by id: params[:id]
  end

  def create
  end

  def update
  end

  def destroy
  end

  def pend
    @applet.pend! if @applet.may_pend?

    redirect_to ifttb_applets_path if @applet.pending?
  end

  def connect
  end

  def disconnect
  end

  private

  def load_applet
    @applet = current_user.applets.find params[:applet_id]
  end
end

app/controllers/ifttb/archived_applets_controller.rb
# frozen_string_literal: true

class Ifttb::ArchivedAppletsController < Ifttb::BaseController
  before_action :load_applet, only: %i[update destroy]

  def index
    @pagy, @applets = pagy current_user.applets.only_archived.order(updated_at: :desc)
  end

  def update
    @applet.archive!
    redirect_to ifttb_applet_path(@applet)
  end

  def destroy
    @applet.update archived_at: nil
    redirect_to ifttb_applet_path(@applet)
  end

  private

  def load_applet
    @applet = current_user.applets.find params[:id]
  end
end

app/controllers/ifttb/base_controller.rb
# frozen_string_literal: true

class Ifttb::BaseController < ApplicationController
  layout 'ifttb'
end

app/controllers/ifttb/home_controller.rb
# frozen_string_literal: true

module Ifttb
  class HomeController < Ifttb::BaseController
    def menu
    end
  end
end

app/controllers/ifttb/orders_controller.rb
# frozen_string_literal: true

class Ifttb::OrdersController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/ifttb/stats_controller.rb
# frozen_string_literal: true

class Ifttb::StatsController < ApplicationController
  def show
  end
end

app/controllers/ifttb/wallet_controller.rb
# frozen_string_literal: true

class Ifttb::WalletController < ApplicationController
  def show
  end

  def withdraw
  end
end

app/views/ifttb/applets/_applet.html.erb
<div id="<%= dom_id applet %>" class="card w-full bg-base-100 shadow-xl">
  <div class="card-body">
    <div class="flex justify-between">
      <span class="opacity-50">#<%= applet.number %></span>
      <%= link_to 'Edit', edit_ifttb_applet_path(applet), class: "" unless applet.connected? %>
    </div>

    <%= link_to ifttb_applet_path(applet) do %>
      <%= render "ifttb/applets/description", applet: applet %>
    <% end %>

    <% if applet.archived? %>
      <div class="flex justify-between text-sm">
        <span class="opacity-75">Archived at:</span>
          <span class="opacity-75"> <%= applet.archived_at.strftime("%D %H:%M") %></span>
      </div>
    <% else %>
      <div class="flex justify-between text-sm">
        <span class="opacity-75">Connected:</span>
        <input type="checkbox" class="toggle" <%= applet.connected && "checked" %> />
      </div>

      <div class="flex justify-between text-sm">
        <span class="opacity-75">Last active:</span>
        <span>
          <%= applet.last_active_at.presence || 'Never' %>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/ifttb/applets/_description.html.erb
<div class="text-sm flex space-x-2">
  <span class="font-bold">If</span>
  <div>
    <% applet.applet_triggers.each do |trigger| %>
      <div class="inline">
        <%= applet_trigger_icon trigger, class: 'w-4 h-4 inline' %>
        <%= trigger.description %>;
      </div>
    <% end %>
  </div>
</div>

<div class="text-sm flex space-x-2 mb-4">
  <span class="font-bold">Then</span>
  <div>
    <% applet.applet_actions.each do |action| %>
      <div>
        <%= applet_action_icon action, class: 'w-4 h-4 inline' %>
        <%= action.description %>;
      </div>
    <% end %>
  </div>
</div>

app/views/ifttb/applets/edit.html.erb
<div class="px-4">
  <div class="mb-8">
    <div class="mb-4 text-lg font-bold">
      Triggers:
    </div>

    <% @applet.applet_triggers.each do |trigger| %>
      <% case trigger.type %>
      <% when 'AppletDatetimeTrigger' %>
        <%= render "ifttb/applet_datetime_triggers/applet_datetime_trigger", trigger: trigger %>
      <% when 'Applet4swapTrigger' %>
        <%= render "ifttb/applet_4swap_triggers/applet_4swap_trigger", trigger: trigger %>
      <% when 'AppletPandoLeafTrigger' %>
        <%= render "ifttb/applet_pando_leaf_triggers/applet_pando_leaf_trigger", trigger: trigger %>
      <% when 'AppletPandoRingsTrigger' %>
        <%= render "ifttb/applet_pando_rings_triggers/applet_pando_rings_trigger", trigger: trigger %>
      <% when 'AppletExinLocalTrigger' %>
        <%= render "ifttb/applet_exin_local_triggers/applet_exin_local_trigger", trigger: trigger %>
      <% end %>
    <% end %>

    <% if @applet.applet_triggers.count < 2 %>
      <div class="flex justify-center">
        <%= render "components/modal" do |p| %>
          <% p.content_for :title, 'Select Trigger' %>
          <% p.content_for :trigger do %>
            <% if @applet.applet_triggers.count == 0 %>
              <div class="btn btn-wide btn-primary btn-md rounded-full text-xl">
                <%= t('add_trigger') %>
              </div>
            <% else %>
              <div class="btn btn-outline btn-sm rounded-full text-3xl">
                +
              </div>
            <% end %>
          <% end %>

          <% p.content_for :body do %>
            <%= render "ifttb/applet_triggers/options", applet: @applet %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="mb-16">
    <div class="mb-4 text-lg font-bold">
      Actions:
    </div>

    <div class="mb-4">
      <% case @applet.applet_action&.type %>
      <% when 'Applet4swapAction' %>
        <%= render "ifttb/applet_4swap_actions/applet_4swap_action", action: @applet.applet_action %>
      <% when 'AppletMixSwapAction' %>
        <%= render "ifttb/applet_mix_swap_actions/applet_mix_swap_action", action: @applet.applet_action %>
      <% when 'AppletAlertAction' %>
        <%= render "ifttb/applet_alert_actions/applet_alert_action", action: @applet.applet_action %>
      <% end %>
    </div>

    <% if @applet.applet_action.blank? %>
      <div class="flex justify-center">
        <%= render "components/modal" do |p| %>
          <% p.content_for :title, 'Select Action' %>
          <% p.content_for :trigger do %>
            <div class="btn btn-wide btn-primary btn-md rounded-full text-xl">
              <%= t('add_action') %>
            </div>
          <% end %>

          <% p.content_for :body do %>
            <%= render "ifttb/applet_actions/options", applet: @applet %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if @applet.may_pend? %>
    <%= link_to 'Continue', 
      ifttb_applet_pend_path(@applet), 
      data: {
        turbo_method: :post
      },
      class: "btn btn-block btn-lg btn-primary rounded-full" %>
  <% else %>
    <%= link_to 'Update', 
      ifttb_applet_path(@applet), 
      class: "btn btn-block btn-lg btn-primary rounded-full" %>
  <% end %>
</div>

<% content_for :navbar do %>
  <div class="relative mb-6 h-12 px-4 py-2 mb-4 text-xl font-bold text-center max-w-screen-lg mx-auto">
    Create Applet
    <%= link_to :back, class: 'absolute left-4' do %>
      <%= inline_svg_tag 'icons/chevron-left.svg', class: 'inline-block' %>
    <% end %>
  </div>
<% end %>

app/views/ifttb/applets/index.html.erb
<div class="pt-4">
  <div class="text-center mb-4">
    You have created <%= current_user.applets.without_drafted.without_archived.count %>/3 applets.
  </div>

  <%= turbo_frame_tag "applets" do %>
    <div id="applets-list" class="px-4 grid sm:grid-cols-2 gap-4">
      <%= render partial: "ifttb/applets/applet", collection: @applets, as: :applet %>
    </div>
    <div id="applets-pagination">
      <%= link_to 'Load More', pagy_url_for(@pagy, @pagy.next), class: 'btn btn-outline btn-wide block mx-auto' if @pagy.next.present? %>
    </div>
  <% end %>
</div>

<% content_for :navbar do %>
  <div class="h-12 px-4 py-2 text-xl font-bold text-white bg-neutral">
    <div class="mx-auto max-w-screen-lg">
      IFTT<span class='text-2xl text-btc'>₿</span>
    </div>
  </div>
<% end %>

<% if current_user.present? %>
  <% content_for :tabbar do %>
    <div class="flex items-center justify-around p-4 mx-auto max-w-screen-lg">
      <% if current_user.may_create_applet? %>
        <%= link_to t('create'), new_ifttb_applet_path, class: 'btn btn-primary btn-sm rounded-full' %>
      <% else %>
        <%= link_to t('upgrade_pro'), new_ifttb_order_path, class: 'btn btn-primary btn-sm rounded-full' %>
      <% end %>

      <%= render "components/modal" do |p| %>
        <% p.content_for :title, 'More' %>
        <% p.content_for :trigger do %>
          <div class="btn btn-primary btn-sm rounded-full">
            <%= inline_svg_tag "icons/bars.svg", class: "w-7 h-7 rounded-full" %>
          </div>
        <% end %>
        <% p.content_for :body do %>
          <%= link_to t('wallet'), ifttb_wallet_path, class: 'btn btn-block btn-primary mb-4' %>
          <%= link_to t('stats'), ifttb_stats_path, class: 'btn btn-block btn-primary mb-4' %>
          <%= link_to t('archived_applets'), ifttb_archived_applets_path, class: 'btn btn-block btn-primary' %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/ifttb/applets/show.html.erb
<div class="px-6">
  <div class="flex justify-between mb-4">
    <span class="opacity-50">#<%= @applet.number %></span>
    <% if @applet.profit.present? %>
      <span>
        <%= @applet.profit %>
      </span>
    <% end %>
  </div>

  <div class="mb-4">
    <%= render "ifttb/applets/description", applet: @applet %>
  </div>

  <% if @applet.archived? %>
    <div class="flex justify-between text-sm mb-4">
      <span class="opacity-75">Archived at:</span>
        <span class="opacity-75"> <%= @applet.archived_at.strftime("%D %H:%M") %></span>
    </div>
  <% else %>
    <div class="flex justify-between text-sm mb-4">
      <span class="opacity-75">Connected:</span>
      <input type="checkbox" class="toggle" <%= @applet.connected && "checked" %> />
    </div>
  <% end %>

  <div class="tabs tabs-boxed w-full">
    <div class="tab tab-active tab-md w-1/2">Stats</div>
    <div class="tab tab-md w-1/2">Activities</div>
  </div>
</div>

<% content_for :navbar do %>
  <div class="relative mb-6 h-12 px-4 py-2 mb-4 text-xl font-bold text-center max-w-screen-lg mx-auto">
    Applet Detail
    <%= link_to ifttb_applets_path, class: 'absolute left-4' do %>
      <%= inline_svg_tag 'icons/chevron-left.svg', class: 'inline-block' %>
    <% end %>
  </div>
<% end %>

<% content_for :tabbar do %>
  <div class="flex items-center justify-around p-4 mx-auto max-w-screen-lg">
    <% if @applet.archived? %>
      <%= button_to t('resume'), 
        ifttb_archived_applet_path(@applet), 
        method: :delete,
        class: 'btn btn-primary btn-sm rounded-full' %>
    <% else %>
      <%= button_to t('archive'), 
        ifttb_archived_applet_path(@applet), 
        method: :put,
        class: 'btn btn-warning btn-ghost btn-sm text-warning rounded-full' %>
    <% end %>
    <%= link_to t('edit'), 
      edit_ifttb_applet_path(@applet), 
      class: 'btn btn-primary btn-sm rounded-full' %>
  </div>
<% end %>